-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `workspace`;
USE SCHEMA `default`;

-- COMMAND ----------

CREATE OR REPLACE TABLE contamination_expantion AS
SELECT 
  ce.*,
  w.Precipitation,
  w.TAVG
FROM contamination_expantion ce
LEFT JOIN (
  SELECT
    Country, City, Date, 
    AVG(Precipitation) as Precipitation,
    AVG(TAVG) as TAVG
  FROM weatherclean
  GROUP BY Country, City, Date
) w
USING (Country, City, Date);
